title: Sarah Mangrum # your name (or website title) here
logo:"/images/IMG_6429.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Healthcare Professional
  Animal Lover. TV Junkie. Love for Learning. <br><br>
  <a href="https://www.linkedin.com/in/sarahamangrum/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
